==widget==
widget.template=template
widget.title=basic timer widget
widget.style=main.css

==manifest==
header.text=Steve second timer widget
component.timer=clock
component.input=slider
component.button=go

==end==
